"""fix relations between models

Revision ID: 31b1ed9f9adb
Revises: 355bf8a8cf03
Create Date: 2023-04-02 18:05:47.251452

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "31b1ed9f9adb"
down_revision = "355bf8a8cf03"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("yt_accounts", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_unique_constraint(None, "yt_accounts", ["user_id"])
    op.create_foreign_key(None, "yt_accounts", "users", ["user_id"], ["id"])
    op.add_column(
        "yt_playlists", sa.Column("yt_account_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "yt_playlists", "yt_accounts", ["yt_account_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "yt_playlists", type_="foreignkey")
    op.drop_column("yt_playlists", "yt_account_id")
    op.drop_constraint(None, "yt_accounts", type_="foreignkey")
    op.drop_constraint(None, "yt_accounts", type_="unique")
    op.drop_column("yt_accounts", "user_id")
    # ### end Alembic commands ###
