"""create tables

Revision ID: 355bf8a8cf03
Revises:
Create Date: 2023-03-31 20:43:55.093673

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "355bf8a8cf03"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "yt_accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("header_auth", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "yt_playlists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("privacy", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("thumbnails", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("author", sa.String(), nullable=True),
        sa.Column("year", sa.String(), nullable=True),
        sa.Column("duration", sa.String(), nullable=True),
        sa.Column("trackCount", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "yt_tracks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("artists", sa.String(), nullable=True),
        sa.Column("album", sa.String(), nullable=True),
        sa.Column("duration", sa.String(), nullable=True),
        sa.Column("thumbnails", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "yt_track_yt_playlist",
        sa.Column("yt_track_id", sa.Integer(), nullable=False),
        sa.Column("yt_playlist_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["yt_playlist_id"],
            ["yt_playlists.id"],
        ),
        sa.ForeignKeyConstraint(
            ["yt_track_id"],
            ["yt_tracks.id"],
        ),
        sa.PrimaryKeyConstraint("yt_track_id", "yt_playlist_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("yt_track_yt_playlist")
    op.drop_table("yt_tracks")
    op.drop_table("yt_playlists")
    op.drop_table("yt_accounts")
    op.drop_table("users")
    # ### end Alembic commands ###
